module.exports = {
  apps : [{
    name: 'hjy-talk',
    script: './server/express.js',
    instances: 'max',
    exec_mode: 'cluster',
    watch: true,
    max_memory_restart: '150M',
    ignore_watch : [
        'node_modules',
        'logs',
        'public',
    ],
    error_log: './logs/express-error.loh',
    out_file: './logs/express-out.log',
    merge_logs: true,
    log_date_format: 'YYYY-MM-DD HH:mm:ss',
    min_uptime: '60s',
    max_restarts: 30,
    autorestart: true,
    restart_delay: '60',
  },
    {
      name: 'hjy-talk-websocket',
      script: './server/socket.js',
      instances: 'max',
      exec_mode: 'fork',
      watch: true,
      max_memory_restart: '150M',
      ignore_watch : [
        'node_modules',
        'logs',
        'public',
      ],
      error_log: './logs/socket-error.loh',
      out_file: './logs/socket-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      min_uptime: '60s',
      max_restarts: 30,
      autorestart: true,
      restart_delay: '60',
    }],
}
